#! /bin/sh

### BEGIN INIT INFO
# Provides:          nttraffd
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: nttraffd
# Description:       nttraffd Traffic Bandwidth Logger
### END INIT INFO

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME="nttraffd"
DAEMON="/usr/local/bin/nttraffd"

case "$1" in
  start)
        log_daemon_msg "Starting nttraff Daemon" "$NAME"
        start-stop-daemon --start --quiet --background --pidfile "/var/run/$NAME.pid" --exec "$DAEMON"
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Stopping nttraff Daemon" "$NAME"
        start-stop-daemon --stop --quiet --pidfile "/var/run/$NAME.pid" --retry=TERM/30/KILL/5
        rm -f "/var/run/$NAME.pid"
        log_end_msg $?
        ;;
  restart)
        $0 stop
        sleep 3
        $0 start
        ;;
  *)
        log_success_msg "Usage: /etc/init.d/nttraffd {start|stop|restart}"
        exit 1
        ;;
esac

exit 0